export const pictures = [
  {
    id: 0,
    name: 'Рождение Венеры',
    author: 'Сандро Боттичелли',
    cost: '1 000 000',
    prevCost: '2 000 000',
    img: '/pictures/venus.jpg',
    isSold: false,
    description: '',
    slides: ['', '', ''],
  },
  {
    id: 1,
    name: 'Тайная вечеря',
    author: 'Леонардо да Винчи',
    cost: '3 000 000',
    prevCost: '',
    img: '/pictures/sacrament.jpg',
    isSold: false,
    description: '',
    slides: ['', '', ''],
  },
  {
    id: 2,
    name: 'Сотворение Адама',
    author: 'Микеланджело',
    cost: '5 000 000',
    prevCost: '6 000 000',
    img: '/pictures/adam.jpg',
    isSold: false,
    description: '',
    slides: ['', '', ''],
  },
  {
    id: 3,
    name: 'Урок анатомии',
    author: 'Рембрандт',
    cost: '',
    prevCost: '',
    img: '/pictures/anatomy.jpg',
    isSold: true,
    description: '',
    slides: ['', '', ''],
  },
]